//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECGWorkStation.RecordUploader {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RecordUploader.FileUploaderSoap")]
    public interface FileUploaderSoap {
        
        // CODEGEN: Generating message contract since element name data from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UploadECGRecord", ReplyAction="*")]
        ECGWorkStation.RecordUploader.UploadECGRecordResponse UploadECGRecord(ECGWorkStation.RecordUploader.UploadECGRecordRequest request);
        
        // CODEGEN: Generating message contract since element name data from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UploadECGRecord2", ReplyAction="*")]
        ECGWorkStation.RecordUploader.UploadECGRecord2Response UploadECGRecord2(ECGWorkStation.RecordUploader.UploadECGRecord2Request request);
        
        // CODEGEN: Generating message contract since element name data from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UploadDiseasePattern", ReplyAction="*")]
        ECGWorkStation.RecordUploader.UploadDiseasePatternResponse UploadDiseasePattern(ECGWorkStation.RecordUploader.UploadDiseasePatternRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadECGRecordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadECGRecord", Namespace="http://tempuri.org/", Order=0)]
        public ECGWorkStation.RecordUploader.UploadECGRecordRequestBody Body;
        
        public UploadECGRecordRequest() {
        }
        
        public UploadECGRecordRequest(ECGWorkStation.RecordUploader.UploadECGRecordRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UploadECGRecordRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] data;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string fileName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string recordID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string PID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.DateTime datetime;
        
        public UploadECGRecordRequestBody() {
        }
        
        public UploadECGRecordRequestBody(byte[] data, string fileName, string recordID, string PID, System.DateTime datetime) {
            this.data = data;
            this.fileName = fileName;
            this.recordID = recordID;
            this.PID = PID;
            this.datetime = datetime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadECGRecordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadECGRecordResponse", Namespace="http://tempuri.org/", Order=0)]
        public ECGWorkStation.RecordUploader.UploadECGRecordResponseBody Body;
        
        public UploadECGRecordResponse() {
        }
        
        public UploadECGRecordResponse(ECGWorkStation.RecordUploader.UploadECGRecordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UploadECGRecordResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UploadECGRecordResult;
        
        public UploadECGRecordResponseBody() {
        }
        
        public UploadECGRecordResponseBody(string UploadECGRecordResult) {
            this.UploadECGRecordResult = UploadECGRecordResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadECGRecord2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadECGRecord2", Namespace="http://tempuri.org/", Order=0)]
        public ECGWorkStation.RecordUploader.UploadECGRecord2RequestBody Body;
        
        public UploadECGRecord2Request() {
        }
        
        public UploadECGRecord2Request(ECGWorkStation.RecordUploader.UploadECGRecord2RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UploadECGRecord2RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] data;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string fileName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string recordID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string PID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.DateTime datetime;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int totalTime;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string docID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string docName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public int heartRate;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public float R;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public int QR;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public int RS;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public int QRS;
        
        public UploadECGRecord2RequestBody() {
        }
        
        public UploadECGRecord2RequestBody(byte[] data, string fileName, string recordID, string PID, System.DateTime datetime, int totalTime, string docID, string docName, int heartRate, float R, int QR, int RS, int QRS) {
            this.data = data;
            this.fileName = fileName;
            this.recordID = recordID;
            this.PID = PID;
            this.datetime = datetime;
            this.totalTime = totalTime;
            this.docID = docID;
            this.docName = docName;
            this.heartRate = heartRate;
            this.R = R;
            this.QR = QR;
            this.RS = RS;
            this.QRS = QRS;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadECGRecord2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadECGRecord2Response", Namespace="http://tempuri.org/", Order=0)]
        public ECGWorkStation.RecordUploader.UploadECGRecord2ResponseBody Body;
        
        public UploadECGRecord2Response() {
        }
        
        public UploadECGRecord2Response(ECGWorkStation.RecordUploader.UploadECGRecord2ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UploadECGRecord2ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UploadECGRecord2Result;
        
        public UploadECGRecord2ResponseBody() {
        }
        
        public UploadECGRecord2ResponseBody(string UploadECGRecord2Result) {
            this.UploadECGRecord2Result = UploadECGRecord2Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadDiseasePatternRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadDiseasePattern", Namespace="http://tempuri.org/", Order=0)]
        public ECGWorkStation.RecordUploader.UploadDiseasePatternRequestBody Body;
        
        public UploadDiseasePatternRequest() {
        }
        
        public UploadDiseasePatternRequest(ECGWorkStation.RecordUploader.UploadDiseasePatternRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UploadDiseasePatternRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] data;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string fileName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string patternID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string patternName;
        
        public UploadDiseasePatternRequestBody() {
        }
        
        public UploadDiseasePatternRequestBody(byte[] data, string fileName, string patternID, string patternName) {
            this.data = data;
            this.fileName = fileName;
            this.patternID = patternID;
            this.patternName = patternName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadDiseasePatternResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadDiseasePatternResponse", Namespace="http://tempuri.org/", Order=0)]
        public ECGWorkStation.RecordUploader.UploadDiseasePatternResponseBody Body;
        
        public UploadDiseasePatternResponse() {
        }
        
        public UploadDiseasePatternResponse(ECGWorkStation.RecordUploader.UploadDiseasePatternResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UploadDiseasePatternResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UploadDiseasePatternResult;
        
        public UploadDiseasePatternResponseBody() {
        }
        
        public UploadDiseasePatternResponseBody(string UploadDiseasePatternResult) {
            this.UploadDiseasePatternResult = UploadDiseasePatternResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FileUploaderSoapChannel : ECGWorkStation.RecordUploader.FileUploaderSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FileUploaderSoapClient : System.ServiceModel.ClientBase<ECGWorkStation.RecordUploader.FileUploaderSoap>, ECGWorkStation.RecordUploader.FileUploaderSoap {
        
        public FileUploaderSoapClient() {
        }
        
        public FileUploaderSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FileUploaderSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileUploaderSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileUploaderSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ECGWorkStation.RecordUploader.UploadECGRecordResponse ECGWorkStation.RecordUploader.FileUploaderSoap.UploadECGRecord(ECGWorkStation.RecordUploader.UploadECGRecordRequest request) {
            return base.Channel.UploadECGRecord(request);
        }
        
        public string UploadECGRecord(byte[] data, string fileName, string recordID, string PID, System.DateTime datetime) {
            ECGWorkStation.RecordUploader.UploadECGRecordRequest inValue = new ECGWorkStation.RecordUploader.UploadECGRecordRequest();
            inValue.Body = new ECGWorkStation.RecordUploader.UploadECGRecordRequestBody();
            inValue.Body.data = data;
            inValue.Body.fileName = fileName;
            inValue.Body.recordID = recordID;
            inValue.Body.PID = PID;
            inValue.Body.datetime = datetime;
            ECGWorkStation.RecordUploader.UploadECGRecordResponse retVal = ((ECGWorkStation.RecordUploader.FileUploaderSoap)(this)).UploadECGRecord(inValue);
            return retVal.Body.UploadECGRecordResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ECGWorkStation.RecordUploader.UploadECGRecord2Response ECGWorkStation.RecordUploader.FileUploaderSoap.UploadECGRecord2(ECGWorkStation.RecordUploader.UploadECGRecord2Request request) {
            return base.Channel.UploadECGRecord2(request);
        }
        
        public string UploadECGRecord2(byte[] data, string fileName, string recordID, string PID, System.DateTime datetime, int totalTime, string docID, string docName, int heartRate, float R, int QR, int RS, int QRS) {
            ECGWorkStation.RecordUploader.UploadECGRecord2Request inValue = new ECGWorkStation.RecordUploader.UploadECGRecord2Request();
            inValue.Body = new ECGWorkStation.RecordUploader.UploadECGRecord2RequestBody();
            inValue.Body.data = data;
            inValue.Body.fileName = fileName;
            inValue.Body.recordID = recordID;
            inValue.Body.PID = PID;
            inValue.Body.datetime = datetime;
            inValue.Body.totalTime = totalTime;
            inValue.Body.docID = docID;
            inValue.Body.docName = docName;
            inValue.Body.heartRate = heartRate;
            inValue.Body.R = R;
            inValue.Body.QR = QR;
            inValue.Body.RS = RS;
            inValue.Body.QRS = QRS;
            ECGWorkStation.RecordUploader.UploadECGRecord2Response retVal = ((ECGWorkStation.RecordUploader.FileUploaderSoap)(this)).UploadECGRecord2(inValue);
            return retVal.Body.UploadECGRecord2Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ECGWorkStation.RecordUploader.UploadDiseasePatternResponse ECGWorkStation.RecordUploader.FileUploaderSoap.UploadDiseasePattern(ECGWorkStation.RecordUploader.UploadDiseasePatternRequest request) {
            return base.Channel.UploadDiseasePattern(request);
        }
        
        public string UploadDiseasePattern(byte[] data, string fileName, string patternID, string patternName) {
            ECGWorkStation.RecordUploader.UploadDiseasePatternRequest inValue = new ECGWorkStation.RecordUploader.UploadDiseasePatternRequest();
            inValue.Body = new ECGWorkStation.RecordUploader.UploadDiseasePatternRequestBody();
            inValue.Body.data = data;
            inValue.Body.fileName = fileName;
            inValue.Body.patternID = patternID;
            inValue.Body.patternName = patternName;
            ECGWorkStation.RecordUploader.UploadDiseasePatternResponse retVal = ((ECGWorkStation.RecordUploader.FileUploaderSoap)(this)).UploadDiseasePattern(inValue);
            return retVal.Body.UploadDiseasePatternResult;
        }
    }
}
